### ISSUE TITLE
User can view products in selected categories

### ISSUE THREAD

**Issue by VeraYeh** [VeraYeh/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view products in selected categories

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a link for each product categories on home page for users to choose category they want to view.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/76827487/126416518-2e47b77b-70e5-4152-9b94-cdd7349ba839.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML structure for the home page.
- [ ] Create HTML structure for the product page.
- [x] Create links to each product page.
- [x] Create link for home page to return to home.
- [ ] Create CSS styling for home and product pages.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
